name: DS535_Fashion
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python==3.9.18
  - pip
  - numpy==1.26.2
  - ipykernel==6.25.0
  - matplotlib==3.8.0
  - datasets==2.15.0
  - tqdm==4.65.0
  - jupyter==1.0.0
  - ipywidgets==8.1.1
  - ipykernel
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.0.0+cu118
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torchvision==0.15.0+cu118
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torchaudio==2.0.0+cu118
    - denoising_diffusion_pytorch==1.9.4
    